### ISSUE TITLE
ListAdapter

### ISSUE THREAD

**Issue by alfianyusufabdullah** [alfianyusufabdullah/AlquranQ#2]
Change RecyclerView.Adapter to ListAdapter

**Comment by NayakNavin** [comment]
can i work on this ?

**Comment by alfianyusufabdullah** [comment]
@NayakNavin yes you can

**Comment by Geanik** [comment]
hey
short tip
maybe assign @NayakNavin  this issue
I'm searching for unassigned Hacktoberfest issues
and I found this one
would make searching easier
thx

**Comment by antercepter** [comment]
@alfianyusufabdullah Does anybody work on this issue? I can take it, if it's not started yet.

**Comment by alfianyusufabdullah** [comment]
@antercepter sure go ahead

**Comment by antercepter** [comment]
@alfianyusufabdullah Before the start, can I ask why do you need to replace `RecyclerView.Adapter` with `ListAdapter`? All works fine and looks good for me :)

**Comment by alfianyusufabdullah** [comment]
@antercepter before I tried it, I just wanted to see what if this was made by another developer

**Comment by alfianyusufabdullah** [comment]
Fixed #2
